module.exports = {
    classes: {
        0: "Tous",
        1: "Nom commun",
        2: "Nom propre",
        3: "Verbe",
        4: "Adjectif",
        5: "Adverbe",
        6: "Conjonction",
        7: "Adjectif démonstratif",
        8: "Pronom",
        9: "Particule",
        10: "Expression",
        11: "Copule",
        12: "Nombre",
        13: "Suffixe",
    },
    collections: {
        0: "Tous",
        1: "150 kanjis essentiels",
        2: "Mots occidentaux kanatakinés",
        3: "Jukujikun",
        4: "Julien Fontanier Sensei",
    },
    kinds: {
        0: "Eléments",
        1: "Kanjis",
        2: "Vocabulaire",
    },
    languages: {
        "DE": "De l'allemand",
        "EN": "De l'anglais",
        "ES": "De l'espagnol",
        "FR": "Du français",
        "IT": "De l'italien",
        "KR": "Du coréen",
        "NL": "Du néerlandais",
        "PT": "Du portugais",
        "RU": "Du russe",
        "ZH": "Du chinois",
    },
    levels: {
        0: "Tous",
        1: "N5",
        2: "N4",
        3: "N3",
        4: "N2",
        5: "N1",
        6: null,
    },
    pluralClasses: {
        0: "Tous",
        1: "Noms communs",
        2: "Noms propres",
        3: "Verbes",
        4: "Adjectifs",
        5: "Adverbes",
        6: "Conjonctions",
        7: "Démonstratifs",
        8: "Pronoms",
        9: "Particules",
        10: "Expressions",
        11: "Copule",
        12: "Nombres",
        13: "Suffixes",
    },
    verbGrammar: {
        'transitive': 'transitif',
        'intransitive': 'intransitif'
    },
}